//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paintbot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal colorContainerHeight_mm {
            get {
                return ((decimal)(this["colorContainerHeight_mm"]));
            }
            set {
                this["colorContainerHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal zMoveHeight_mm {
            get {
                return ((decimal)(this["zMoveHeight_mm"]));
            }
            set {
                this["zMoveHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal brushsize_mm {
            get {
                return ((decimal)(this["brushsize_mm"]));
            }
            set {
                this["brushsize_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosY_mm {
            get {
                return ((decimal)(this["colorPosY_mm"]));
            }
            set {
                this["colorPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosX_mm {
            get {
                return ((decimal)(this["colorPosX_mm"]));
            }
            set {
                this["colorPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosZ_mm {
            get {
                return ((decimal)(this["colorPosZ_mm"]));
            }
            set {
                this["colorPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public decimal xySpeed_mm_min {
            get {
                return ((decimal)(this["xySpeed_mm_min"]));
            }
            set {
                this["xySpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal pickColorFrequency {
            get {
                return ((decimal)(this["pickColorFrequency"]));
            }
            set {
                this["pickColorFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal zSpeed_mm_min {
            get {
                return ((decimal)(this["zSpeed_mm_min"]));
            }
            set {
                this["zSpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeEnd.txt")]
        public string gcodeEndPath {
            get {
                return ((string)(this["gcodeEndPath"]));
            }
            set {
                this["gcodeEndPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeStart.txt")]
        public string gcodeStartPath {
            get {
                return ((string)(this["gcodeStartPath"]));
            }
            set {
                this["gcodeStartPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\out\\")]
        public string outputPath {
            get {
                return ((string)(this["outputPath"]));
            }
            set {
                this["outputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\in.bmp")]
        public string imagePath {
            get {
                return ((string)(this["imagePath"]));
            }
            set {
                this["imagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffffff")]
        public string ignoreColor_hex {
            get {
                return ((string)(this["ignoreColor_hex"]));
            }
            set {
                this["ignoreColor_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public decimal zDepth_mm {
            get {
                return ((decimal)(this["zDepth_mm"]));
            }
            set {
                this["zDepth_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool colorAtYgantry {
            get {
                return ((bool)(this["colorAtYgantry"]));
            }
            set {
                this["colorAtYgantry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flipYAxis {
            get {
                return ((bool)(this["flipYAxis"]));
            }
            set {
                this["flipYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool endOverPaint {
            get {
                return ((bool)(this["endOverPaint"]));
            }
            set {
                this["endOverPaint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool moveZXsameTime {
            get {
                return ((bool)(this["moveZXsameTime"]));
            }
            set {
                this["moveZXsameTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal canvasZeroPosX_mm {
            get {
                return ((decimal)(this["canvasZeroPosX_mm"]));
            }
            set {
                this["canvasZeroPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosY_mm {
            get {
                return ((decimal)(this["canvasZeroPosY_mm"]));
            }
            set {
                this["canvasZeroPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosZ_mm {
            get {
                return ((decimal)(this["canvasZeroPosZ_mm"]));
            }
            set {
                this["canvasZeroPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int progressbar {
            get {
                return ((int)(this["progressbar"]));
            }
            set {
                this["progressbar"] = value;
            }
        }
    }
}
