//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paintbot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal colorContainerHeight_mm {
            get {
                return ((decimal)(this["colorContainerHeight_mm"]));
            }
            set {
                this["colorContainerHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal zMoveHeight_mm {
            get {
                return ((decimal)(this["zMoveHeight_mm"]));
            }
            set {
                this["zMoveHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal brushsize_mm {
            get {
                return ((decimal)(this["brushsize_mm"]));
            }
            set {
                this["brushsize_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosY_mm {
            get {
                return ((decimal)(this["colorPosY_mm"]));
            }
            set {
                this["colorPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosX_mm {
            get {
                return ((decimal)(this["colorPosX_mm"]));
            }
            set {
                this["colorPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosZ_mm {
            get {
                return ((decimal)(this["colorPosZ_mm"]));
            }
            set {
                this["colorPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public decimal xySpeed_mm_min {
            get {
                return ((decimal)(this["xySpeed_mm_min"]));
            }
            set {
                this["xySpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal pickColorFrequency {
            get {
                return ((decimal)(this["pickColorFrequency"]));
            }
            set {
                this["pickColorFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal zSpeed_mm_min {
            get {
                return ((decimal)(this["zSpeed_mm_min"]));
            }
            set {
                this["zSpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeEnd.txt")]
        public string gcodeEndPath {
            get {
                return ((string)(this["gcodeEndPath"]));
            }
            set {
                this["gcodeEndPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeStart.txt")]
        public string gcodeStartPath {
            get {
                return ((string)(this["gcodeStartPath"]));
            }
            set {
                this["gcodeStartPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\out\\")]
        public string outputPath {
            get {
                return ((string)(this["outputPath"]));
            }
            set {
                this["outputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string imagePath {
            get {
                return ((string)(this["imagePath"]));
            }
            set {
                this["imagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffffffff")]
        public string ignoreColor_hex {
            get {
                return ((string)(this["ignoreColor_hex"]));
            }
            set {
                this["ignoreColor_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public decimal zDepth_mm {
            get {
                return ((decimal)(this["zDepth_mm"]));
            }
            set {
                this["zDepth_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool colorAtYgantry {
            get {
                return ((bool)(this["colorAtYgantry"]));
            }
            set {
                this["colorAtYgantry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flipYAxis {
            get {
                return ((bool)(this["flipYAxis"]));
            }
            set {
                this["flipYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool endOverWater {
            get {
                return ((bool)(this["endOverWater"]));
            }
            set {
                this["endOverWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool moveZXsameTime {
            get {
                return ((bool)(this["moveZXsameTime"]));
            }
            set {
                this["moveZXsameTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal canvasZeroPosX_mm {
            get {
                return ((decimal)(this["canvasZeroPosX_mm"]));
            }
            set {
                this["canvasZeroPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosY_mm {
            get {
                return ((decimal)(this["canvasZeroPosY_mm"]));
            }
            set {
                this["canvasZeroPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosZ_mm {
            get {
                return ((decimal)(this["canvasZeroPosZ_mm"]));
            }
            set {
                this["canvasZeroPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int progressbar {
            get {
                return ((int)(this["progressbar"]));
            }
            set {
                this["progressbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("905")]
        public decimal maxWidthX {
            get {
                return ((decimal)(this["maxWidthX"]));
            }
            set {
                this["maxWidthX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1640")]
        public decimal maxHeightY {
            get {
                return ((decimal)(this["maxHeightY"]));
            }
            set {
                this["maxHeightY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a101/ffffffff/10,0/-10,0\na139/ffecda3e/10,1/-10,1\na102/fff4ed56/10,2/-10,2\na121/f" +
            "feecf3d/10,3/-10,3\na140/ffe39d33/10,4/-10,4\na134/ff8369bf/10,5/-10,5\na125/ff3c33" +
            "33/10,6/-10,6\na111/ff433866/10,7/-10,7\na110/ff4b4273/10,8/-10,8\na116/ff3c334d/10" +
            ",9/-10,9\na113/ffcf9a38/10,10/-10,10\na127/ffb48347/10,11/-10,11\na144/ffa97537/10," +
            "12/-10,12\na131/fff1d69e/10,13/-10,13\na148/ffde7b2d/10,14/-10,14\na152/ffb4553d/10" +
            ",15/-10,15\na114/ffdc5b2c/10,16/-10,16\na126/ffd94834/10,17/-10,17\na129/ffd0a574/1" +
            "0,18/-10,18\na106/ffd73d35/10,19/-10,19\na145/ffda4538/10,20/-10,20\na142/ffd83f38/" +
            "10,21/-10,21\na161/ffd93c44/10,22/-10,22\na155/ffce383c/10,23/-10,23\na105/ffd13d43" +
            "/10,24/-10,24\na150/ff9a3138/10,25/-10,25\na138/ffd1333c/19/-103\na115/ffd51e81/10," +
            "27/-10,27\na146/ffdc37be/10,28/-10,28\na157/ffdb4f76/10,29/-10,29\na141/ffe59cd0/10" +
            ",30/-10,30\na135/fff4e2b7/10,31/-10,31\na124/ff7197f7/10,32/-10,32\na147/ff5d84dd/1" +
            "0,33/-10,33\na123/ff5d8ee1/10,34/-10,34\na154/ff69a1f5/10,35/-10,35\na120/ff72c898/" +
            "10,36/-10,36\na103/ff262c3a/10,37/-10,37\na136/ff40706e/10,38/-10,38\na122/ff294321" +
            "/10,39/-10,39\na158/ff282d39/10,40/-10,40\na143/ff325719/10,41/-10,41\na149/ff41684" +
            "d/10,42/-10,42\na159/ff4c8a54/10,43/-10,43\na109/ff6ec856/18/-244\na156/ff52911f/10" +
            ",45/-10,45\na137/ff5f643c/10,46/-10,46\na119/ffbb843a/10,47/-10,47\na118/ff42372f/1" +
            "0,48/-10,48\na130/ff6b5340/10,49/-10,49\na108/ff5b3a31/10,50/-10,50\na151/ff833130/" +
            "10,51/-10,51\na107/ff9a4635/10,52/-10,52\na153/ff5a392f/10,53/-10,53\na160/ff2a292e" +
            "/10,54/-10,54\na162/ff38302d/10,55/-10,55\na112/ff000000/10/-12\na132/ffb0b1b5/10,5" +
            "7/-10,57\na117/ffb3c8e5/10,58/-10,58\na128/ffcacace/10,59/-10,59\n")]
        public string colorDefinitions {
            get {
                return ((string)(this["colorDefinitions"]));
            }
            set {
                this["colorDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool centerOnCanvas {
            get {
                return ((bool)(this["centerOnCanvas"]));
            }
            set {
                this["centerOnCanvas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useColorPosDef {
            get {
                return ((bool)(this["useColorPosDef"]));
            }
            set {
                this["useColorPosDef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal maxNumColorPerFile {
            get {
                return ((decimal)(this["maxNumColorPerFile"]));
            }
            set {
                this["maxNumColorPerFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosX_mm {
            get {
                return ((decimal)(this["waterPosX_mm"]));
            }
            set {
                this["waterPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosY_mm {
            get {
                return ((decimal)(this["waterPosY_mm"]));
            }
            set {
                this["waterPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosZ_mm {
            get {
                return ((decimal)(this["waterPosZ_mm"]));
            }
            set {
                this["waterPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal cleanBrushPicks {
            get {
                return ((decimal)(this["cleanBrushPicks"]));
            }
            set {
                this["cleanBrushPicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0file")]
        public string filePrefix {
            get {
                return ((string)(this["filePrefix"]));
            }
            set {
                this["filePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal colorMoveRadius {
            get {
                return ((decimal)(this["colorMoveRadius"]));
            }
            set {
                this["colorMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal waterMoveRadius {
            get {
                return ((decimal)(this["waterMoveRadius"]));
            }
            set {
                this["waterMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal spongeMoveRadius {
            get {
                return ((decimal)(this["spongeMoveRadius"]));
            }
            set {
                this["spongeMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal tissueMoveRadius {
            get {
                return ((decimal)(this["tissueMoveRadius"]));
            }
            set {
                this["tissueMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosX_mm {
            get {
                return ((decimal)(this["spongePosX_mm"]));
            }
            set {
                this["spongePosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosY_mm {
            get {
                return ((decimal)(this["spongePosY_mm"]));
            }
            set {
                this["spongePosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosZ_mm {
            get {
                return ((decimal)(this["spongePosZ_mm"]));
            }
            set {
                this["spongePosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosX_mm {
            get {
                return ((decimal)(this["tissuePosX_mm"]));
            }
            set {
                this["tissuePosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosY_mm {
            get {
                return ((decimal)(this["tissuePosY_mm"]));
            }
            set {
                this["tissuePosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosZ_mm {
            get {
                return ((decimal)(this["tissuePosZ_mm"]));
            }
            set {
                this["tissuePosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useSponge {
            get {
                return ((bool)(this["useSponge"]));
            }
            set {
                this["useSponge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useWater {
            get {
                return ((bool)(this["useWater"]));
            }
            set {
                this["useWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useTissue {
            get {
                return ((bool)(this["useTissue"]));
            }
            set {
                this["useTissue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal minCircleDiameterPixel {
            get {
                return ((decimal)(this["minCircleDiameterPixel"]));
            }
            set {
                this["minCircleDiameterPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal maxCircleDiameterPixel {
            get {
                return ((decimal)(this["maxCircleDiameterPixel"]));
            }
            set {
                this["maxCircleDiameterPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string amountOfCircles {
            get {
                return ((string)(this["amountOfCircles"]));
            }
            set {
                this["amountOfCircles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRectangleErase {
            get {
                return ((bool)(this["useRectangleErase"]));
            }
            set {
                this["useRectangleErase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool filterResizeRecolor {
            get {
                return ((bool)(this["filterResizeRecolor"]));
            }
            set {
                this["filterResizeRecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal groupColorFactor {
            get {
                return ((decimal)(this["groupColorFactor"]));
            }
            set {
                this["groupColorFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string amountOfColors {
            get {
                return ((string)(this["amountOfColors"]));
            }
            set {
                this["amountOfColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public decimal waterContainerHeight_mm {
            get {
                return ((decimal)(this["waterContainerHeight_mm"]));
            }
            set {
                this["waterContainerHeight_mm"] = value;
            }
        }
    }
}
