//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paintbot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal colorContainerHeight_mm {
            get {
                return ((decimal)(this["colorContainerHeight_mm"]));
            }
            set {
                this["colorContainerHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal zMoveHeight_mm {
            get {
                return ((decimal)(this["zMoveHeight_mm"]));
            }
            set {
                this["zMoveHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal brushsize_mm {
            get {
                return ((decimal)(this["brushsize_mm"]));
            }
            set {
                this["brushsize_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosY_mm {
            get {
                return ((decimal)(this["colorPosY_mm"]));
            }
            set {
                this["colorPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosX_mm {
            get {
                return ((decimal)(this["colorPosX_mm"]));
            }
            set {
                this["colorPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal colorPosZ_mm {
            get {
                return ((decimal)(this["colorPosZ_mm"]));
            }
            set {
                this["colorPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public decimal xySpeed_mm_min {
            get {
                return ((decimal)(this["xySpeed_mm_min"]));
            }
            set {
                this["xySpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal pickColorFrequency {
            get {
                return ((decimal)(this["pickColorFrequency"]));
            }
            set {
                this["pickColorFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public decimal zSpeed_mm_min {
            get {
                return ((decimal)(this["zSpeed_mm_min"]));
            }
            set {
                this["zSpeed_mm_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeEnd.txt")]
        public string gcodeEndPath {
            get {
                return ((string)(this["gcodeEndPath"]));
            }
            set {
                this["gcodeEndPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\conf\\gcodeStart.txt")]
        public string gcodeStartPath {
            get {
                return ((string)(this["gcodeStartPath"]));
            }
            set {
                this["gcodeStartPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Paintbot\\out\\")]
        public string outputPath {
            get {
                return ((string)(this["outputPath"]));
            }
            set {
                this["outputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string imagePath {
            get {
                return ((string)(this["imagePath"]));
            }
            set {
                this["imagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ignoreColor_hex {
            get {
                return ((string)(this["ignoreColor_hex"]));
            }
            set {
                this["ignoreColor_hex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5")]
        public decimal zDepth_mm {
            get {
                return ((decimal)(this["zDepth_mm"]));
            }
            set {
                this["zDepth_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool colorAtYgantry {
            get {
                return ((bool)(this["colorAtYgantry"]));
            }
            set {
                this["colorAtYgantry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool flipYAxis {
            get {
                return ((bool)(this["flipYAxis"]));
            }
            set {
                this["flipYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool endOverWater {
            get {
                return ((bool)(this["endOverWater"]));
            }
            set {
                this["endOverWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool moveZXsameTime {
            get {
                return ((bool)(this["moveZXsameTime"]));
            }
            set {
                this["moveZXsameTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal canvasZeroPosX_mm {
            get {
                return ((decimal)(this["canvasZeroPosX_mm"]));
            }
            set {
                this["canvasZeroPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosY_mm {
            get {
                return ((decimal)(this["canvasZeroPosY_mm"]));
            }
            set {
                this["canvasZeroPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10")]
        public decimal canvasZeroPosZ_mm {
            get {
                return ((decimal)(this["canvasZeroPosZ_mm"]));
            }
            set {
                this["canvasZeroPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int progressbar {
            get {
                return ((int)(this["progressbar"]));
            }
            set {
                this["progressbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("905")]
        public decimal maxWidthX {
            get {
                return ((decimal)(this["maxWidthX"]));
            }
            set {
                this["maxWidthX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1640")]
        public decimal maxHeightY {
            get {
                return ((decimal)(this["maxHeightY"]));
            }
            set {
                this["maxHeightY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"a101/ffffffff/42/-748
a102/fff4ed56/72/-748
a103/ff262c3a/102/-748
a105/ffd13d43/132/-748
a106/ffd73d35/162/-748
a107/ff9a4635/192/-748
a108/ff5b3a31/222/-748
a109/ff6ec856/270/-748
a110/ff4b4273/300/-748
a111/ff433866/330/-748
a112/ff000000/360/-748
a113/ffcf9a38/390/-748
a114/ffdc5b2c/420/-748
a115/ffd51e81/450/-748
a116/ff3c334d/498/-748
a117/ffb3c8e5/528/-748
a118/ff42372f/558/-748
a119/ffbb843a/588/-748
a120/ff72c898/618/-748
a121/ffeecf3d/648/-748
a122/ff294321/678/-748
a123/ff5d8ee1/42/-780
a124/ff7197f7/72/-780
a125/ff3c3333/102/-780
a126/ffd94834/132/-780
a127/ffb48347/162/-780
a128/ffcacace/192/-780
a129/ffd0a574/222/-780
a130/ff6b5340/270/-780
a131/fff1d69e/300/-780
a132/ffb0b1b5/330/-780
a134/ff8369bf/360/-780
a135/fff4e2b7/390/-780
a136/ff40706e/420/-780
a137/ff5f643c/450/-780
a138/ffd1333c/498/-780
a139/ffecda3e/528/-780
a140/ffe39d33/558/-780
a141/ffe59cd0/588/-780
a142/ffd83f38/618/-780
a143/ff325719/648/-780
a144/ffa97537/678/-780
a145/ffda4538/42/-816
a146/ffdc37be/72/-816
a147/ff5d84dd/102/-816
a148/ffde7b2d/132/-816
a149/ff41684d/162/-816
a150/ff9a3138/192/-816
a151/ff833130/222/-816
a152/ffb4553d/270/-816
a153/ff5a392f/300/-816
a154/ff69a1f5/330/-816
a155/ffce383c/360/-816
a156/ff52911f/390/-816
a157/ffdb4f76/420/-816
a158/ff282d39/450/-816
a159/ff4c8a54/498/-816
a160/ff2a292e/528/-816
a161/ffd93c44/558/-816
a162/ff38302d/588/-816")]
        public string colorDefinitions {
            get {
                return ((string)(this["colorDefinitions"]));
            }
            set {
                this["colorDefinitions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool centerOnCanvas {
            get {
                return ((bool)(this["centerOnCanvas"]));
            }
            set {
                this["centerOnCanvas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useColorPosDef {
            get {
                return ((bool)(this["useColorPosDef"]));
            }
            set {
                this["useColorPosDef"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal maxNumColorPerFile {
            get {
                return ((decimal)(this["maxNumColorPerFile"]));
            }
            set {
                this["maxNumColorPerFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosX_mm {
            get {
                return ((decimal)(this["waterPosX_mm"]));
            }
            set {
                this["waterPosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosY_mm {
            get {
                return ((decimal)(this["waterPosY_mm"]));
            }
            set {
                this["waterPosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal waterPosZ_mm {
            get {
                return ((decimal)(this["waterPosZ_mm"]));
            }
            set {
                this["waterPosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal cleanBrushPicks {
            get {
                return ((decimal)(this["cleanBrushPicks"]));
            }
            set {
                this["cleanBrushPicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0file")]
        public string filePrefix {
            get {
                return ((string)(this["filePrefix"]));
            }
            set {
                this["filePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal colorMoveRadius {
            get {
                return ((decimal)(this["colorMoveRadius"]));
            }
            set {
                this["colorMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal waterMoveRadius {
            get {
                return ((decimal)(this["waterMoveRadius"]));
            }
            set {
                this["waterMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal spongeMoveRadius {
            get {
                return ((decimal)(this["spongeMoveRadius"]));
            }
            set {
                this["spongeMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal tissueMoveRadius {
            get {
                return ((decimal)(this["tissueMoveRadius"]));
            }
            set {
                this["tissueMoveRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosX_mm {
            get {
                return ((decimal)(this["spongePosX_mm"]));
            }
            set {
                this["spongePosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosY_mm {
            get {
                return ((decimal)(this["spongePosY_mm"]));
            }
            set {
                this["spongePosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal spongePosZ_mm {
            get {
                return ((decimal)(this["spongePosZ_mm"]));
            }
            set {
                this["spongePosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosX_mm {
            get {
                return ((decimal)(this["tissuePosX_mm"]));
            }
            set {
                this["tissuePosX_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosY_mm {
            get {
                return ((decimal)(this["tissuePosY_mm"]));
            }
            set {
                this["tissuePosY_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal tissuePosZ_mm {
            get {
                return ((decimal)(this["tissuePosZ_mm"]));
            }
            set {
                this["tissuePosZ_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useSponge {
            get {
                return ((bool)(this["useSponge"]));
            }
            set {
                this["useSponge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useWater {
            get {
                return ((bool)(this["useWater"]));
            }
            set {
                this["useWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool useTissue {
            get {
                return ((bool)(this["useTissue"]));
            }
            set {
                this["useTissue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal minCircleDiameterPixel {
            get {
                return ((decimal)(this["minCircleDiameterPixel"]));
            }
            set {
                this["minCircleDiameterPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal maxCircleDiameterPixel {
            get {
                return ((decimal)(this["maxCircleDiameterPixel"]));
            }
            set {
                this["maxCircleDiameterPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string amountOfCircles {
            get {
                return ((string)(this["amountOfCircles"]));
            }
            set {
                this["amountOfCircles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useRectangleErase {
            get {
                return ((bool)(this["useRectangleErase"]));
            }
            set {
                this["useRectangleErase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool filterResizeRecolor {
            get {
                return ((bool)(this["filterResizeRecolor"]));
            }
            set {
                this["filterResizeRecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal groupColorFactor {
            get {
                return ((decimal)(this["groupColorFactor"]));
            }
            set {
                this["groupColorFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string amountOfColors {
            get {
                return ((string)(this["amountOfColors"]));
            }
            set {
                this["amountOfColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public decimal waterContainerHeight_mm {
            get {
                return ((decimal)(this["waterContainerHeight_mm"]));
            }
            set {
                this["waterContainerHeight_mm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal wiggleAmountWater {
            get {
                return ((decimal)(this["wiggleAmountWater"]));
            }
            set {
                this["wiggleAmountWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal wiggleAmountSponge {
            get {
                return ((decimal)(this["wiggleAmountSponge"]));
            }
            set {
                this["wiggleAmountSponge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal wiggleAmountTissue {
            get {
                return ((decimal)(this["wiggleAmountTissue"]));
            }
            set {
                this["wiggleAmountTissue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal wiggleAmountColor {
            get {
                return ((decimal)(this["wiggleAmountColor"]));
            }
            set {
                this["wiggleAmountColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cleanBrushStart {
            get {
                return ((bool)(this["cleanBrushStart"]));
            }
            set {
                this["cleanBrushStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pixelFileLimit {
            get {
                return ((bool)(this["pixelFileLimit"]));
            }
            set {
                this["pixelFileLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool resizeColorGcode {
            get {
                return ((bool)(this["resizeColorGcode"]));
            }
            set {
                this["resizeColorGcode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool xzMoveStroke {
            get {
                return ((bool)(this["xzMoveStroke"]));
            }
            set {
                this["xzMoveStroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool endInWater {
            get {
                return ((bool)(this["endInWater"]));
            }
            set {
                this["endInWater"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal brushXmoveStroke {
            get {
                return ((decimal)(this["brushXmoveStroke"]));
            }
            set {
                this["brushXmoveStroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G90 ; use absolute positioning for the XYZ axes")]
        public string gcodeStart {
            get {
                return ((string)(this["gcodeStart"]));
            }
            set {
                this["gcodeStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gcodeEnd {
            get {
                return ((string)(this["gcodeEnd"]));
            }
            set {
                this["gcodeEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\\nG53\"")]
        public string gCodeMoveType {
            get {
                return ((string)(this["gCodeMoveType"]));
            }
            set {
                this["gCodeMoveType"] = value;
            }
        }
    }
}
